<?xml version="1.0" ?>
<!-- $Id $ -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="text"/>
	<xsl:template match="/data">
Invoice notifications have been produced for <xsl:value-of select="cycle_date"/>

Total number of online billing subscribers for this cycle: <xsl:value-of select="subscriber_count"/>
Total number of email notifications produced for this cycle: <xsl:value-of select="notification_count"/>

This report was generated by program <xsl:value-of select="program_name"/> (JCL <xsl:value-of select="jcl_name"/>)

**This is an automatically generated email. Please do not respond**
	</xsl:template>
</xsl:stylesheet>
